const {test}=require('node:test');
const assert=require('node:assert/strict');
const http=require('node:http');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const {makeHandler}=require('../server/handler');
const {passwordHash,digest}=require('../server/security');
test('controle de acesso completo e vínculo exclusivo',async t=>{
 const pg=new PGlite(); await pg.exec(fs.readFileSync('server/schema.sql','utf8'));
 const db={query:(...args)=>pg.query(...args),connect:async()=>({query:(...args)=>pg.query(...args),release(){}})};
 const config={NODE_ENV:'test',ADMIN_USERNAME:'admin-test',ADMIN_PASSWORD_HASH:await passwordHash('test-password')};
 const server=http.createServer(makeHandler(async()=>db,config));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin=`http://127.0.0.1:${server.address().port}`;config.APP_ORIGIN=origin;
 t.after(async()=>{await new Promise(r=>server.close(r));await pg.close()});
 function browser(){const jar={};return async(path,body,override={})=>{const res=await fetch(origin+path,{method:body?'POST':'GET',redirect:'manual',headers:{origin,'content-type':'application/json',cookie:Object.entries(jar).map(([k,v])=>`${k}=${v}`).join('; '),...override},...(body?{body:JSON.stringify(body)}:{})});for(const c of res.headers.getSetCookie()){const [k,v]=c.split(';')[0].split('=');jar[k]=v;}return res;};}
 const admin=browser(),a=browser(),b=browser();
 assert.equal((await a('/questions.js')).status,303);
 assert.equal((await a('/human-rights.js')).status,303);
 assert.equal((await admin('/api/login',{mode:'admin',username:'admin-test',password:'wrong'})).status,401);
 assert.equal((await admin('/api/login',{mode:'admin',username:'admin-test',password:'test-password'})).status,200);
 assert.equal((await admin('/api/admin/keys',{name:'Aluno'},{origin:'https://evil.invalid'})).status,403);
 const created=await admin('/api/admin/keys',{name:'Aluno'});assert.equal(created.status,201);const {key,id}=await created.json();
 const row=(await pg.query('SELECT * FROM gcm_keys')).rows[0];assert.equal(row.key_hash,digest(key));assert.notEqual(row.key_hash,key);
 const first=await Promise.all([a('/api/login',{key}),b('/api/login',{key})]);assert.deepEqual(first.map(r=>r.status).sort(),[200,403]);
 const good=first[0].status===200?a:b,bad=first[0].status===200?b:a;
 assert.equal((await good('/questions.js')).status,200);
 const material=await good('/human-rights.js');assert.equal(material.status,200);assert.match(await material.text(),/const HUMAN_RIGHTS/);
 assert.equal((await good('/api/admin/keys')).status,403);
 assert.equal((await good('/admin.js')).status,403);
 assert.equal((await good('/admin.html')).status,404);
 assert.equal((await good('/server/schema.sql')).status,404);
 assert.equal((await good('/api/logout',{})).status,200);
 assert.equal((await good('/api/login',{key})).status,200);
 assert.equal((await bad('/api/login',{key})).status,403);
 assert.equal((await admin('/api/admin/action',{id,action:'block'})).status,200);
 assert.equal((await good('/api/me')).status,401);
 assert.equal((await good('/questions.js')).status,303);
 assert.equal((await good('/api/login',{key})).status,403);
 await admin('/api/admin/action',{id,action:'unblock'});
 assert.equal((await good('/api/login',{key})).status,200);
 const replacement=await (await admin('/api/admin/action',{id,action:'replace'})).json();
 assert.equal((await good('/api/me')).status,401);
 assert.equal((await good('/api/login',{key})).status,403);
 assert.equal((await bad('/api/login',{key:replacement.key})).status,200);
 const listing=await (await admin('/api/admin/keys')).json();assert.equal(listing.keys.length,1);assert.equal(listing.keys[0].bound,true);assert.equal(listing.keys[0].key_hash,undefined);
 config.ADMIN_PASSWORD_HASH=await passwordHash('changed-test-password');assert.equal((await admin('/api/me')).status,401);
});
