Object.assign(SOURCES,{"winEncrypt": ["Criptografia de arquivos — Microsoft", "https://support.microsoft.com/pt-br/windows/security/encryption/how-to-encrypt-a-file-or-folder"], "chromeKeys": ["Atalhos do Chrome — Google", "https://support.google.com/chrome/answer/157179?hl=pt-BR"], "chromeCycle": ["Mudança do ciclo do Chrome em 2021 — Chromium", "https://blog.chromium.org/2021/03/speeding-up-release-cycle.html"]});
const COMPUTING_MATERIAL = [
  {
    "id": 201,
    "subject": "inf",
    "topic": "Windows",
    "question": "Considerando o contexto da questão de 2024, qual alternativa identifica a versão mais recente do Microsoft Windows naquele momento?",
    "options": [
      "Windows 11.",
      "Windows 10.",
      "Windows Update.",
      "Microsoft 365.",
      "Microsoft 2024."
    ],
    "correct": 0,
    "explanation": "No contexto de 2024, a resposta indicada é Windows 11, lançado em 2021. A questão foi delimitada à data original e não afirma qual é a versão mais recente hoje.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 1,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: IVIN - Prefeitura de Curuçá - PA - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "Referência temporal explicitada para evitar desatualização.",
    "passage": []
  },
  {
    "id": 202,
    "subject": "inf",
    "topic": "Windows",
    "question": "No sistema operacional Windows, é possível alterar o conteúdo de um arquivo que se encontra aberto em um computador remoto. Assinale a alternativa que indica corretamente a ferramenta do Windows que permite essa ação.",
    "options": [
      "Wordpad ++",
      "Bloco de Notas",
      "Internet Explorer",
      "Explorador de Arquivos",
      "Conexão de Área de Trabalho Remota"
    ],
    "correct": 4,
    "explanation": "Através da Conexão de Área de Trabalho Remota, é possível acessar e controlar um computador remoto como se estivesse fisicamente presente nele. Isso inclui a capacidade de abrir, visualizar e editar arquivos que estão no computador remoto, incluindo a modificação de seu conteúdo.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 2,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: FEPESE - Prefeitura de São José - SC - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 203,
    "subject": "inf",
    "topic": "Windows",
    "question": "No sistema operacional Windows, um aplicativo bastante útil é o Explorador de Arquivos. Com ele podemos criar pastas e arquivos, fazer cópias de arquivos entre dispositivos, além de outras operações. Assinale a alternativa que apresenta uma ação possível de ser realizada pelo Explorador de Arquivos.",
    "options": [
      "Mesclar dois arquivos de texto.",
      "Reproduzir arquivos de áudio ou vídeo.",
      "Comparar o conteúdo de dois arquivos, indicando sua diferença.",
      "Criar um atalho na área de trabalho a partir de um arquivo qualquer.",
      "Criptografar um arquivo texto para que não possa ser lido sem autorização."
    ],
    "correct": 3,
    "explanation": "O Explorador de Arquivos é uma ferramenta do Windows que permite navegar pelos arquivos e pastas do sistema operacional. Com ele, é possível realizar várias ações relacionadas à organização e manipulação de arquivos, incluindo a criação de atalhos na área de trabalho para acesso rápido a arquivos ou pastas específicas.",
    "source": "winEncrypt",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 3,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: FEPESE - Prefeitura de São José - SC - Guarda Municipal.",
    "status": "pending",
    "scopeNote": "O arquivo indica D, mas a opção E também pode ser viável em edições do Windows com criptografia EFS, pelas propriedades do arquivo. Sem delimitar edição e contexto, o item é ambíguo e não pontua.",
    "revision": "Gabarito do PDF preservado apenas para consulta; não apresentado como validado.",
    "passage": []
  },
  {
    "id": 204,
    "subject": "inf",
    "topic": "Windows",
    "question": "Windows é um sistema operacional para computadores desenvolvido pela Microsoft. Existem várias funções principais do sistema operacional Windows. Assinale a alternativa incorreta.",
    "options": [
      "Ser responsável por organizar e gerenciar todos os arquivos do computador",
      "Oferecer uma interface gráfica amigável, com ícones, janelas, menus e barras de tarefas",
      "O único propósito do Windows é gerenciar os softwares que operam no computador",
      "Incluir recursos de segurança para proteger o computador contra malwares e vírus",
      "O Windows é responsável por gerenciar os componentes de hardware do computador"
    ],
    "correct": 2,
    "explanation": "Embora o gerenciamento de softwares seja uma função importante do sistema operacional Windows, ele não é o único propósito do Windows.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 4,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: IBFC - Prefeitura de Manaus - AM - Técnico Municipal I - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 205,
    "subject": "inf",
    "topic": "Windows",
    "question": "No Windows 11, qual dos seguintes atalhos de teclado é usado para renomear um arquivo ou pasta selecionado?",
    "options": [
      "F2.",
      "Ctrl+C.",
      "Alt+Delete.",
      "Shift+R.",
      "F8."
    ],
    "correct": 0,
    "explanation": "F2 renomeia arquivos ou pastas.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 5,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: Instituto Darwin - Prefeitura de Lagoa de Itaenga - PE.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 206,
    "subject": "inf",
    "topic": "Windows",
    "question": "Assinale a opção que indica um sistema operacional utilizado em computadores domésticos.",
    "options": [
      "Microsoft Office 365",
      "Windows Explorer",
      "Windows 10",
      "Google Chrome"
    ],
    "correct": 2,
    "explanation": "O Windows 10 é um sistema operacional da Microsoft.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 6,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de São Cristóvão - SE - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 207,
    "subject": "inf",
    "topic": "Windows",
    "question": "Em um computador com sistema operacional Windows, um documento baixado da Internet será salvo, por padrão, na pasta chamada",
    "options": [
      "Documentos.",
      "Downloads.",
      "Área de Trabalho.",
      "Imagens."
    ],
    "correct": 1,
    "explanation": "Essa pasta é usada pelo sistema operacional Windows como padrão para salvar os arquivos baixados da Internet ou de outros locais.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 7,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de Boa Vista - RR - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 208,
    "subject": "inf",
    "topic": "Windows",
    "question": "Assinale a opção que indica a ferramenta do Windows utilizada para ajuste de configurações do computador.",
    "options": [
      "Explorador de Arquivos",
      "Painel de Controle",
      "Acessórios do Windows",
      "Google Chrome"
    ],
    "correct": 1,
    "explanation": "O Painel de Controle é uma ferramenta central no Windows que permite aos usuários acessarem e ajustarem uma ampla variedade de configurações do sistema.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 8,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de Boa Vista - RR - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 209,
    "subject": "inf",
    "topic": "Windows",
    "question": "Na aparência padrão do Windows considerada pela questão, qual símbolo sobreposto ao ícone identifica um atalho?",
    "options": [
      "Um asterisco preto.",
      "Uma seta azul.",
      "Um mapa cinza.",
      "Um pino prateado.",
      "Um círculo dourado."
    ],
    "correct": 1,
    "explanation": "O símbolo de seta identifica o atalho. Sua cor e aparência podem variar conforme versão e tema; não é correto afirmar que seja sempre azul em qualquer versão.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 9,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2022 Banca: Avança SP - Prefeitura de Laranjal Paulista - SP - Guarda Civil Municipal.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "Removida a afirmação absoluta sobre todas as versões; mantidas as alternativas originais.",
    "passage": []
  },
  {
    "id": 210,
    "subject": "inf",
    "topic": "Windows",
    "question": "Em relação a ampulheta presente no Windows é correto afirmar:",
    "options": [
      "Por padrão demonstra que o Windows está em processamento ou em carregamento de algum software.",
      "Permite executar o Windows Explorer para abrir o Paint.",
      "É utilizado para calcular o nível de desfragmentação do Windows em seus percentuais de progressão.",
      "Permite utilizar pastas somente para realizar cópias em subdiretórios."
    ],
    "correct": 0,
    "explanation": "A ampulheta, também conhecida como \"cursor de espera\" ou \"cursor de ocupado\", é um ícone que aparece quando o sistema operacional Windows está ocupado processando uma tarefa ou carregando algum software. Essa é a função padrão da ampulheta no Windows.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Windows",
    "materialNumber": 10,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2019 Banca: Itame - Prefeitura de Senador Canedo - GO - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 211,
    "subject": "inf",
    "topic": "Office",
    "question": "Tendo por referência os softwares de apresentação de slides, dois recursos são destacados a seguir. I. No Powerpoint 2016 BR, um atalho de teclado deve ser executado para salvar o trabalho feito em um arquivo com formato PPTX. II. No lmpress da suíte LibreOffice 6.3, versão em português, uma tecla de função deve ser acionada para executar a verificação e correção ortográfica. O atalho de teclado e a tecla de função são, respectivamente:",
    "options": [
      "Ctrl + B e F7",
      "Ctrl + S e F7",
      "Ctrl + B e F11",
      "Ctrl + S e F11"
    ],
    "correct": 0,
    "explanation": "Os atalhos para os itens respectivos são Ctrl + B e F7.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 1,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2022 Banca: SELECON - Prefeitura de São Gonçalo - RJ - Guarda Municipal Nível II.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "",
    "passage": []
  },
  {
    "id": 212,
    "subject": "inf",
    "topic": "Office",
    "question": "São funções dos aplicativos que compõem o pacote Microsoft Office, EXCETO:",
    "options": [
      "Administração do fluxo de dados pela rede.",
      "Construção de gráficos e realização de cálculos.",
      "Elaboração de slides e apresentações.",
      "Elaboração de textos diversos."
    ],
    "correct": 0,
    "explanation": "Os aplicativos do pacote Microsoft Office, como o Word, Excel e PowerPoint, são mais conhecidos por suas funcionalidades de elaboração de textos, construção de planilhas e apresentações de slides. Eles são projetados para tarefas de produtividade pessoal, como criar documentos, planilhas e apresentações, e geralmente não estão envolvidos na administração do fluxo de dados pela rede. Portanto, a opção correta é a alternativa A.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 2,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2017 Banca: Crescer Consultorias - Prefeitura de Urbano Santos - MA - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 213,
    "subject": "inf",
    "topic": "Office",
    "question": "Considere as afirmações abaixo sobre os aplicativos dos pacotes Microsoft Office e Open Office I. O Word 2007 abre documento gerado pelo BASIC do pacote Open Office. II. O Excel 2007 abre planilha gerada pelo IMPRE do pacote Open Office. III. O Power Point 2007 abre apresentação gerada pelo PRESENT do Open Office. É INCORRETO o que se afirma em",
    "options": [
      "I e II apenas.",
      "I e III apenas.",
      "II e III apenas.",
      "I, II e III."
    ],
    "correct": 3,
    "explanation": "As três afirmações usam nomes que não correspondem aos aplicativos de produtividade citados. No OpenOffice, o editor de texto é Writer, a planilha é Calc e o editor de apresentações é Impress. BASIC é uma linguagem de programação. A compatibilidade de arquivos depende do formato e da versão.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 3,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2016 Banca: UECE-CEV - Prefeitura de Tianguá - CE.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "Comentário corrigido: “IMPRE” não é o nome do aplicativo de planilhas nem uma denominação oficial do módulo de impressão.",
    "passage": []
  },
  {
    "id": 214,
    "subject": "inf",
    "topic": "Office",
    "question": "As opções Negrito, Itálico e Sublinhado também podem ser encontrados no comando:",
    "options": [
      "Fonte, do menu Formatar.",
      "Parágrafo, do menu Formatar.",
      "Marcadores e Numeração, do menu Formatar.",
      "Bordas e Sombreamento, do menu Formatar.",
      "Colunas, do menu Formatar."
    ],
    "correct": 0,
    "explanation": "Negrito, Itálico e Sublinhado são estilos de fonte. Portanto, pertencem ao grupo Fonte, o qual abrage outros elementos como tamanho e cor das letras.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 4,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Banca: MS CONCURSOS - Guarda Civil Metropolitano.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "",
    "passage": []
  },
  {
    "id": 215,
    "subject": "inf",
    "topic": "Office",
    "question": "Em uma interface clássica do Office com barra de menus, em qual menu se encontra o comando Visualizar impressão?",
    "options": [
      "Menu Inserir.",
      "Menu Tabela.",
      "Menu Exibir.",
      "Menu Arquivo.",
      "Não existe este comando."
    ],
    "correct": 3,
    "explanation": "Na interface clássica, o comando fica no menu Arquivo. O Office 2007 usa o Botão do Office; versões posteriores apresentam Arquivo > Imprimir.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 5,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2011 Banca: MS CONCURSOS Órgão: Prefeitura de São Paulo - SP Prova: MS CONCURSOS - 2011 - Prefeitura de São Paulo - SP - Guarda Civil Metropolitano.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "Contexto de interface clássica explicitado e comentário sobre Office 2007 corrigido.",
    "passage": []
  },
  {
    "id": 216,
    "subject": "inf",
    "topic": "Office",
    "question": "Referente a sessão de atalhos do MS-Office 2010, quais atalhos representam a ação de inserir data e hora respectivamente no texto?",
    "options": [
      "(Shift+Alt+Z) e (Shift+Alt+j)",
      "(Shift+Alt+D) e (Shift+Alt+T)",
      "(Shift+Alt+O) e (Shift+Alt+W)",
      "(Shift+Alt+J) e (Shift+Alt+P)",
      "Nenhuma das alternativas."
    ],
    "correct": 1,
    "explanation": "No caso do Microsoft Office 2010, a combinação (Shift+Alt+D) é o atalho para inserir a data atual e a combinação (Shift+Alt+T) é o atalho para inserir a hora atual.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 6,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2018 Banca: Instituto Excelência - Prefeitura de São Carlos - SP.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "",
    "passage": []
  },
  {
    "id": 217,
    "subject": "inf",
    "topic": "Office",
    "question": "No Word, ao selecionar Layout da Página > Hifenização > Automático, qual será o efeito sobre o texto?",
    "options": [
      "Será habilitado a correção para o idioma padrão de instalação.",
      "O texto será justificado de forma a não ocorrer divisão de palavras, quando estas não caberem inteiramente na linha.",
      "O texto será centralizado de forma homogênea, para que o mesmo fique agradável na leitura",
      "Será dividida a palavra ao trocar de linha quando a mesma não caber inteira nela."
    ],
    "correct": 3,
    "explanation": "Nesse caso ocorrerá a divisão da palavra ao trocar de linho quando não couber totalmente nela.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 7,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2016 Banca: IBFC.",
    "status": "ready",
    "scopeNote": "",
    "revision": "Adaptada para texto: o menu Hifenização mostrado na figura do PDF foi descrito no enunciado.",
    "passage": []
  },
  {
    "id": 218,
    "subject": "inf",
    "topic": "Office",
    "question": "A versão do Microsoft Office que inclui o Word, PowerPoint e o Excel no formato de serviço na nuvem (Cloud Computing) é denominada, pela própria Microsoft, como:",
    "options": [
      "Microsoft Office Real-Time",
      "Microsoft Cloud",
      "Microsoft Office 365",
      "Office Cloud"
    ],
    "correct": 2,
    "explanation": "O Microsoft Office 365 é uma versão do Microsoft Office que oferece acesso aos aplicativos tradicionais do Office, como Word, PowerPoint e Excel, além de outros serviços na nuvem, como armazenamento online, e-mail e colaboração em tempo real. Portanto, a resposta correta é a opção C.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 8,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2015 Banca: IBFC.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "",
    "passage": []
  },
  {
    "id": 219,
    "subject": "inf",
    "topic": "Office",
    "question": "Dentre as opções que a tela de impressão de aplicativos Microsoft Office oferece, NÃO existe uma opção para:",
    "options": [
      "visualizar, na tela do computador, como o documento será impresso antes de imprimi-lo.",
      "imprimir somente parte do documento.",
      "informar o número de cópias que se deseja imprimir.",
      "alterar propriedades como tipo de papel que se está utilizando.",
      "ligar a impressora, caso a mesma esteja desligada no momento da impressão."
    ],
    "correct": 4,
    "explanation": "A tela de impressão dos aplicativos Microsoft Office geralmente oferece opções para visualizar como o documento será impresso antes de imprimi-lo (opção A), imprimir somente parte do documento (opção B), informar o número de cópias que se deseja imprimir (opção C) e alterar propriedades como tipo de papel que se está utilizando (opção D). No entanto, ela não oferece uma opção para ligar a impressora, caso esteja desligada no momento da impressão, pois isso é uma função relacionada ao hardware da impressora e não ao software do Microsoft Office.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 9,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Banca: FUNCAB.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 220,
    "subject": "inf",
    "topic": "Office",
    "question": "No Word, o usuário abre Inserir > Tabela e destaca uma grade de 5 colunas por 2 linhas (indicada como “5x2 Tabela”). Ao confirmar, qual será o resultado?",
    "options": [
      "A importação de uma tabela já existente com 5 colunas e 2 linhas.",
      "A criação de uma nova tabela com 5 colunas e 2 linhas.",
      "A criação de uma sequência de slides de apresentação.",
      "A criação de uma nova tabela com 2 colunas e 5 linhas.",
      "A exclusão dos dados de uma tabela presente no texto, deixando linhas e colunas vazias."
    ],
    "correct": 1,
    "explanation": "O Word criará uma nova tabela com cinco colunas e duas linhas. O recurso ilustrado é do Word, e não do Excel como afirma o comentário do PDF.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Office",
    "materialNumber": 10,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: OBJETIVA - Prefeitura de Canoas - RS - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "Figura convertida em descrição textual; referência ao Excel corrigida para Word.",
    "passage": []
  },
  {
    "id": 221,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "Em ambientes empresariais de menor porte, existe uma topologia de rede que é predominante. Diante do exposto assinale a alternativa que apresenta esta tal topologia de rede predominante.",
    "options": [
      "Estrela",
      "Híbrida",
      "Anel",
      "Espiral",
      "Barramento"
    ],
    "correct": 0,
    "explanation": "A topologia em estrela é uma das mais comuns e amplamente utilizadas atualmente. Nessa configuração, todos os dispositivos são conectados a um único ponto central, como um switch ou um hub. Essa centralização simplifica a administração da rede, facilitando a detecção e resolução de problemas.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 1,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: IBFC - Prefeitura de Manaus - AM - Técnico Municipal I - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 222,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "Qual das seguintes afirmações sobre redes de computadores está CORRETA?",
    "options": [
      "Um switch, também conhecido como comutador de rede, é um dispositivo de rede utilizado para interconectar dispositivos em uma rede local (LAN - Local Area Network).",
      "O IP (Internet Protocol) é um protocolo utilizado exclusivamente para transmissão de dados por redes sem fio, como Wi-Fi, e não é utilizado em redes com fio.",
      "O DNS (Domain Name System) é um protocolo utilizado para proteger a rede contra ataques cibernéticos, impedindo o acesso não autorizado aos recursos e serviços.",
      "O firewall é um tipo de cabo de rede especializado que permite conectar dispositivos em uma rede local (LAN), fornecendo segurança avançada contra ameaças externas.",
      "O roteador é um dispositivo utilizado apenas para conexões de internet por meio de tecnologia dial-up, não sendo necessário em redes de alta velocidade."
    ],
    "correct": 0,
    "explanation": "Um switch é, de fato, um dispositivo de rede utilizado para interconectar dispositivos em uma rede local (LAN). Ele atua na camada de enlace do modelo OSI, direcionando o tráfego apenas para os dispositivos relevantes.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 2,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CPCON - Prefeitura de Dona Inês - PB - Agente Administrativo.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 223,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "Qual protocolo usa criptografia para proteger a comunicação entre o navegador e o servidor de um site?",
    "options": [
      "FTP.",
      "HTTP.",
      "HTTPS.",
      "Telnet.",
      "POP3;"
    ],
    "correct": 2,
    "explanation": "HTTPS protege a comunicação HTTP com TLS. Isso protege os dados em trânsito, mas não garante que o conteúdo do site seja confiável. O símbolo exibido pelo navegador pode variar.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 3,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: MS Concursos e Consultoria Órgão - Prefeitura de Luís Eduardo.",
    "status": "ready",
    "scopeNote": "",
    "revision": "Gabarito corrigido de B para C (HTTPS). Enunciado adaptado para retirar a associação enganosa entre cadeado e confiabilidade do site.",
    "passage": []
  },
  {
    "id": 224,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "Uma rede de computadores é um conjunto de computadores e dispositivos de conexão interligados, executando protocolos e aplicativos para compartilhar informações. As redes de computadores de alcance continental que interligam cidades ou países através de backbones são as redes:",
    "options": [
      "Locais.",
      "De campus.",
      "Metropolitanas.",
      "De longa distância."
    ],
    "correct": 3,
    "explanation": "Essas redes abrangem grandes áreas geográficas e são projetadas para interligar locais distantes, como cidades ou países, possibilitando a comunicação e o compartilhamento de informações em uma escala ampla.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 4,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: Instituto Consulplan - Prefeitura de Vila Velha - ES - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 225,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "“Na topologia _____________ todos os computadores trocam informações entre si através do mesmo cabo, sendo este utilizado para a transmissão de dados entre os computadores. Este tipo de topologia é utilizada na comunicação ponto-a-ponto.” A lacuna deve ser preenchida por:",
    "options": [
      "em anel.",
      "híbrida.",
      "em barramento.",
      "em árvore.",
      "em estrela."
    ],
    "correct": 2,
    "explanation": "Na topologia em barramento, os dispositivos compartilham um meio principal de transmissão. A expressão “ponto-a-ponto” do enunciado é imprecisa para descrever esse meio compartilhado.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 5,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2022 Banca: IBADE - Prefeitura de Barra de São Francisco - ES - Guarda Civil Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "Ressalva técnica ao comentário original: barramento é um meio compartilhado.",
    "passage": []
  },
  {
    "id": 226,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "Existem protocolos que auxiliam no recebimento de mensagens de e-mail. Um deles tem a função de permitir o acesso de mensagens diretamente no servidor, online, em tempo real, e no cliente de e-mail. Qual?",
    "options": [
      "POP3.",
      "IMAP.",
      "SMTP.",
      "TCP.",
      "UDP."
    ],
    "correct": 1,
    "explanation": "O IMAP (Internet Message Access Protocol) é projetado para permitir que um cliente de e-mail acesse mensagens de e-mail diretamente no servidor de e-mail, em tempo real. Isso significa que as mensagens permanecem armazenadas no servidor e podem ser acessadas e gerenciadas por meio de diferentes dispositivos e clientes de e-mail, mantendo a sincronização entre eles. O POP3 (Post Office Protocol 3) também é um protocolo de recebimento de e-mail, mas geralmente faz o download das mensagens para o cliente de e-mail, removendo-as do servidor.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 6,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2022 Banca: IBADE - Prefeitura de Barra de São Francisco - ES - Guarda Civil Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 227,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "O comando de teclado usado no Google Chrome, que tem como finalidade abrir uma nova aba “guia” no navegador é?",
    "options": [
      "CTRL+A.",
      "CTRL+F.",
      "CTRL+N.",
      "CTRL+T.",
      "CTRL+P."
    ],
    "correct": 3,
    "explanation": "Pressionando CTRL+T, você pode abrir uma nova aba no Google Chrome para acessar uma página da web adicional sem fechar a aba atual.",
    "source": "chromeKeys",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 7,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: IVIN - Prefeitura de Curuçá - PA - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "O PDF deixou a letra do gabarito em branco; preenchida com D, Ctrl+T, conforme o comentário e a documentação do Chrome.",
    "passage": []
  },
  {
    "id": 228,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "O Google Chrome, um navegador de internet desenvolvido pela empresa Google, foi lançado pela primeira vez em setembro de 2008, para o Microsoft Windows, e mais tarde foi portado para Linux. Sobre a atualização de tal navegador, assinale a afirmativa correta.",
    "options": [
      "É atualizado a cada 24 horas.",
      "É atualizado anualmente, sempre após a liberação de uma nova versão.",
      "Não requer atualização, pois é o navegador mais seguro existente na atualidade.",
      "É atualizado a cada seis semanas, para que o usuário possa ter os recursos e as correções de segurança mais recentes."
    ],
    "correct": 3,
    "explanation": "O Google Chrome tem um ciclo de lançamento rápido e é atualizado aproximadamente a cada seis semanas. Isso permite que os usuários tenham acesso aos recursos mais recentes, bem como a correções de segurança e melhorias de desempenho de forma regular.",
    "source": "chromeCycle",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 8,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 - Prefeitura de Vila Velha - ES - Guarda Municipal.",
    "status": "pending",
    "scopeNote": "Item desatualizado: a alternativa D usa o antigo ciclo de seis semanas. O Chromium anunciou em 2021 a mudança para quatro semanas; portanto esse gabarito não serve como regra para a questão datada de 2023. O ciclo também pode mudar conforme época e canal. Nenhuma alternativa será validada neste treino.",
    "revision": "Gabarito histórico D preservado apenas para consulta, sem pontuação.",
    "passage": []
  },
  {
    "id": 229,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "No Outlook, a opção utilizada para adicionar um arquivo a uma mensagem de email é",
    "options": [
      "Criar Novo E-mail.",
      "Enviar.",
      "Anexar.",
      "Adicionar um Assunto."
    ],
    "correct": 2,
    "explanation": "Ao redigir um e-mail no Outlook, você pode anexar um arquivo clicando na opção \"Anexar\" e selecionando o arquivo desejado em seu computador. Isso permite que o arquivo seja enviado junto com a mensagem de e-mail.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 9,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de Boa Vista - RR - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 230,
    "subject": "inf",
    "topic": "Internet e redes",
    "question": "Lourdes - BA Prova: Crescer Consultorias - 2017 - Prefeitura de Campo Alegre de Lourdes - BA - Guarda Municipal O principal programa de correio eletrônico da empresa Microsoft é o:",
    "options": [
      "SharePoint.",
      "Outlook.",
      "Publisher.",
      "OneNote."
    ],
    "correct": 1,
    "explanation": "O Microsoft Outlook é um dos principais programas de correio eletrônico (e-mail) desenvolvidos pela Microsoft. Ele é amplamente utilizado para enviar, receber e gerenciar e-mails, além de oferecer recursos adicionais, como calendário, tarefas, contatos e integração com outros serviços da Microsoft, como o Microsoft Exchange Server.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Internet e redes",
    "materialNumber": 10,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2017 Banca: Crescer Consultorias Órgão: Prefeitura de Campo Alegre de.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 231,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "Suponha que um arquivo da Área de Trabalho do computador seja colocado na nuvem. Nesse caso, o arquivo ficará disponível",
    "options": [
      "em uma solução de armazenamento online.",
      "na pasta Documentos do computador.",
      "em um pendrive do usuário.",
      "no armazenamento interno do celular do usuário."
    ],
    "correct": 0,
    "explanation": "Quando um arquivo é colocado na nuvem, ele é armazenado em um servidor remoto em vez de estar localmente no dispositivo. Isso permite que o arquivo seja acessado de qualquer lugar com acesso à internet, por meio de uma solução de armazenamento online, como Google Drive, Dropbox, OneDrive, entre outros.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 1,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de Boa Vista - RR - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 232,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "Considere as seguintes afirmações relativas ao sistema operacional Windows: I. É possível criar um arquivo em uma pasta diretamente no Windows Explorer (Explorador de Arquivos), sem abrir nenhum programa anteriormente; por exemplo, é possível criar um arquivo de texto no Explorador de Arquivos sem uso do Word. II. Os diretórios são locais exclusivamente para armazenamento de arquivos de forma compactada. III. Afora limitações de armazenamento do dispositivo, um diretório pode conter diversos arquivos de diferentes tipos, por exemplo, planilhas eletrônicas, arquivos de texto, arquivos de imagem, etc. É(São) VERDADEIRA(S)",
    "options": [
      "apenas uma dentre as afirmações I, II e III.",
      "I e II, apenas.",
      "I e III, apenas.",
      "II e III, apenas.",
      "I, II e III."
    ],
    "correct": 2,
    "explanation": "I. É possível criar um arquivo em uma pasta diretamente no Windows Explorer (Explorador de Arquivos), sem abrir nenhum programa anteriormente. Isso é verdadeiro. Por exemplo, é possível criar um arquivo de texto no Explorador de Arquivos sem usar o Word.III. Afora limitações de armazenamento do dispositivo, um diretório pode conter diversos arquivos de diferentes tipos, como planilhas eletrônicas, arquivos de texto, arquivos de imagem, etc. Isso também é verdadeiro. Um diretório pode conter vários tipos de arquivos, desde que haja espaço de armazenamento disponível.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 2,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2022 Banca: UPENET/IAUPE Órgão: Prefeitura de São Lourenço da Mata - PE Prova: UPENET/IAUPE - 2022 - Prefeitura de São Lourenço da Mata - PE - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 233,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "No Explorador de Arquivos do Windows 10, uma pasta exibe seus arquivos em linhas, com colunas Nome, Data de modificação, Tipo e Tamanho. Como se chama esse modo de exibição?",
    "options": [
      "Lista",
      "Detalhes",
      "Ícones médios",
      "Ícones grandes"
    ],
    "correct": 1,
    "explanation": "Tanto o modo de exibição lista, quanto o modo de exibição detalhes aparecem verticalmente com o nome do arquivo ao lado (igual a figura da questão), mas para diferenciá-los basta olhar os arquivos. Se aparece data e hora, tipo e tamanho do arquivo, o modo de exibição será detalhes. Portanto, o gabarito da questão é letra B.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 3,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2020 Banca: SELECON - Prefeitura de Boa Vista - RR - Guarda Civil Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "Figura e alternativas gráficas transcritas em texto após conferência visual do PDF.",
    "passage": []
  },
  {
    "id": 234,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "São nomes de arquivos válidos no Windows 7:",
    "options": [
      "PRN e LPT1",
      "AUX1 e UM=DOIS",
      "LPT1 e AUX1",
      "NUL e PRN",
      "AUX e PRN"
    ],
    "correct": 1,
    "explanation": "Os dois são permitidos pelo Windows.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 4,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2019 Banca: COSEAC - Prefeitura de Maricá - RJ - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "",
    "passage": []
  },
  {
    "id": 235,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "O Explorador de Arquivos está na pasta D:\\Program Files\\Java\\jdk1.8.0_161. O que acontece ao clicar na seta para cima, ao lado da barra de endereço?",
    "options": [
      "mostre o conteúdo da última pasta visitada.",
      "mostre o conteúdo da pasta “Java”.",
      "abra uma lista dos locais recentes.",
      "mostre o conteúdo da pasta “Dados (D:)”.",
      "faça o upload do conteúdo da pasta atual para a nuvem."
    ],
    "correct": 1,
    "explanation": "A seta para cima abre a pasta pai do local atual: Java. Ela não equivale ao botão Voltar, que percorre o histórico de navegação.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 5,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2019 Banca: FGV Órgão: Prefeitura de Salvador - BA Provas: FGV - 2019 -.",
    "status": "ready",
    "scopeNote": "",
    "revision": "Caminho da figura transcrito e diferença entre pasta pai e histórico corrigida.",
    "passage": []
  },
  {
    "id": 236,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "Avalie as seguintes afirmações em relação ao recurso de Acesso Rápido do Explorador de Arquivos do Windows 10. I. Quando o Explorador de Arquivos for aberto, você entrará no Acesso rápido. As pastas usadas com frequência e os arquivos usados recentemente ficam listados. II. Se você quiser que uma pasta apareça no Acesso rápido, clique nela com o botão direito do mouse e selecione Fixar no Acesso rápido. III. Não é possível fixar no Acesso Rápido uma pasta que você armazenou no pendrive.",
    "options": [
      "Todos os itens estão corretos.",
      "Apenas os itens I e II estão corretos.",
      "Apenas os itens I e III estão corretos.",
      "Apenas os itens II e III estão corretos."
    ],
    "correct": 1,
    "explanation": "I. Correto. Quando o Explorador de Arquivos é aberto, você entra no Acesso Rápido, onde as pastas usadas com frequência e os arquivos usados recentemente são listados. II. Correto. Para fixar uma pasta no Acesso Rápido, você pode clicar com o botão direito do mouse na pasta desejada e selecionar \"Fixar no Acesso Rápido\". III. Incorreto. Você pode fixar no Acesso Rápido uma pasta que esteja armazenada em um pendrive, desde que o pendrive esteja conectado ao computador.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 6,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2018 Banca: IMA - Prefeitura de Caxias - MA - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 237,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "No Windows Explorer do MS-Windows 7, em sua configuração padrão, um usuário decide excluir um arquivo. Após selecionar o arquivo e apertar apenas a tecla Delete, uma janela solicita confirmação para mover o arquivo para",
    "options": [
      "Lixeira",
      "Área de Trabalho",
      "Pasta Downloads",
      "Pasta Documentos",
      "C:\\"
    ],
    "correct": 0,
    "explanation": "Ao excluir um arquivo no Windows, por padrão, ele é movido para a Lixeira, onde pode ser recuperado posteriormente, se necessário. Portanto, ao pressionar a tecla Delete, o sistema solicitará confirmação para mover o arquivo selecionado para a Lixeira.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 7,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2018 Banca: VUNESP - Prefeitura de Suzano - SP - Guarda Civil Municipal.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "",
    "passage": []
  },
  {
    "id": 238,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "No Windows 10, Maria deseja renomear Agenda.txt para um nome relacionado a janeiro de 2018. Considerando os caracteres permitidos pelo sistema, qual nome é aceito?",
    "options": [
      "Agenda jan/2018.",
      "Agenda jan-2018.",
      "Agenda jan|2018.",
      "Agenda jan:2018.",
      "Agenda jan*2018."
    ],
    "correct": 1,
    "explanation": "O caractere de hífen é permitido pelo Windows em nome de pastas e arquivos.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 8,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2017 Banca: FUNDATEC Órgão: Prefeitura de Esteio - RS Provas: FUNDATEC - 2017 - Prefeitura de Esteio - RS - Técnico Florestal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "Enunciado simplificado: removidas instruções sobre figuras de outras questões; alternativas preservadas.",
    "passage": []
  },
  {
    "id": 239,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "No Explorador de Arquivos do Windows 10, a pasta C:\\Cadastro contém o arquivo Agenda.txt e a subpasta Clientes, ambos na mesma unidade. O usuário arrasta Agenda.txt com o botão esquerdo para Clientes e solta, sem pressionar teclas modificadoras. O que acontece?",
    "options": [
      "Copiado para a pasta “Cadastro”.",
      "Copiado para a pasta “Clientes”.",
      "Duplicado para a pasta “Clientes”.",
      "Duplicado para a pasta “Cadastro”.",
      "Movido para a pasta “Clientes”."
    ],
    "correct": 4,
    "explanation": "Ao arrastar com o botão esquerdo dentro da mesma unidade, sem teclas modificadoras, a operação padrão é mover. Entre unidades diferentes, normalmente é copiar. A distinção relevante é a unidade, não apenas a mudança de diretório.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 9,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2017 Banca: FUNDATEC - 2017 - Prefeitura de Esteio - RS - Técnico Florestal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "Figura descrita no enunciado; comentário corrigido sobre movimentação na mesma unidade.",
    "passage": []
  },
  {
    "id": 240,
    "subject": "inf",
    "topic": "Arquivos e pastas",
    "question": "No Windows XP, qual procedimento permite alterar o nome de uma pasta existente?",
    "options": [
      "Usar exclusivamente o botão Ir.",
      "Clicar com o botão direito na pasta e escolher Renomear.",
      "Criar três subpastas dentro dela.",
      "Alterar apenas o modo de exibição dos arquivos.",
      "Não é possível renomear pastas."
    ],
    "correct": 1,
    "explanation": "Clicando com o botão direito do mouse sobre a pasta em questão é possível utilizar as funcionalidades da opção Renomear encontrada por meio do menu que aparece em decorrência desta ação.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Arquivos e pastas",
    "materialNumber": 10,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2012 Banca: CEC - Prefeitura de Pinhais - PR - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Questão histórica ou dependente de versão/idioma. Treine considerando o contexto indicado; os menus e atalhos podem variar entre versões.",
    "revision": "Questão adaptada: as alternativas que dependiam de ícones pequenos foram reescritas, preservando o conceito e a resposta correta.",
    "passage": []
  },
  {
    "id": 241,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "O firewall exerce uma função crucial em sistemas computacionais. Assinale a alternativa que apresenta a função crucial.",
    "options": [
      "Otimizar o desempenho do sistema",
      "Monitorar e controlar o tráfego de rede",
      "Fazer backup automático de arquivos",
      "Gerenciar senhas de usuários",
      "Monitorar a velocidade da Internet"
    ],
    "correct": 1,
    "explanation": "O firewall é uma parte essencial da segurança de rede, monitorando e controlando o tráfego de rede com base em regras definidas. Ele atua como uma barreira entre uma rede interna confiável e redes externas não confiáveis, como a Internet, ajudando a proteger contra ameaças e ataques cibernéticos. Portanto, a resposta correta é a alternativa B.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 1,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: IBFC - Prefeitura de Manaus - AM - Técnico Municipal I - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 242,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "Segurança da informação é a proteção de dados de propriedade das organizações contra perigos e ameaças diversas, envolvendo ações que objetivam evitar riscos e garantir a continuidade das operações. Entre os princípios da segurança da informação, um tem por principal objetivo preservar o sigilo dos dados, significando que certas informações não devem ser acessadas por pessoas que não sejam credenciadas, nem divulgadas por essas pessoas com fins obscuros. Esse princípio é conhecido por:",
    "options": [
      "integridade",
      "autenticidade",
      "confidencialidade",
      "vulnerabilidade"
    ],
    "correct": 2,
    "explanation": "O princípio da segurança da informação que tem por principal objetivo preservar o sigilo dos dados, significando que certas informações não devem ser acessadas por pessoas que não sejam credenciadas, nem divulgadas por essas pessoas com fins obscuros é conhecido por confidencialidade.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 2,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: IDECAN - Prefeitura de Fortaleza - CE - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 243,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "O software que monitora uma rede de computadores e bloqueia ou permite a liberação do tráfego de dados a partir de regras predefinidas é denominado",
    "options": [
      "antispyware.",
      "firewall.",
      "antivírus.",
      "antispam."
    ],
    "correct": 1,
    "explanation": "Um firewall é uma medida de segurança de rede que monitora e controla o tráfego de entrada e saída com base em regras de segurança definidas. Ele pode bloquear ou permitir o tráfego com base em várias características, como endereço IP, porta e protocolo.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 3,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de São Cristóvão - SE - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 244,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "Assinale a opção que corresponde ao software malicioso que prejudica o computador do usuário, é ativado sem a necessidade de ação humana e se replica automaticamente, de forma independente.",
    "options": [
      "vírus",
      "ransomware",
      "worm",
      "spam"
    ],
    "correct": 2,
    "explanation": "Os worms são tipos de malware que se espalham automaticamente pela rede, aproveitando falhas de segurança e vulnerabilidades nos sistemas. Eles podem se auto-replicar e se espalhar para outros computadores sem a interação do usuário, tornando-os uma ameaça significativa à segurança da rede.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 4,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de São Cristóvão - SE - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 245,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "Assinale a opção que corresponde ao tipo de fraude em que, por meio de um link recebido por email, um usuário acessa uma página falsa na Internet, sem saber da sua falsidade, e nela digita informações pessoais como senhas ou dados de cartão de crédito.",
    "options": [
      "hacker",
      "vírus",
      "antivírus",
      "phishing"
    ],
    "correct": 3,
    "explanation": "O phishing é uma forma de fraude na qual os criminosos tentam obter informações confidenciais, como senhas, números de cartão de crédito e informações de login, fingindo ser uma entidade confiável em uma comunicação eletrônica. Eles geralmente usam e-mails falsos que direcionam os usuários para sites fraudulentos que se parecem com sites legítimos, para que possam capturar as informações inseridas pelos usuários.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 5,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de Boa Vista - RR - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 246,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "Assinale a opção que indica um programa que, se existente no computador, poderá protegê-lo de um arquivo malicioso baixado da Internet.",
    "options": [
      "Lixeira",
      "antivírus",
      "Limpeza de Disco",
      "Explorador de Arquivos"
    ],
    "correct": 1,
    "explanation": "Os antivírus são programas projetados para detectar, prevenir e remover malware, como vírus, worms, trojans e spyware, de um computador. Eles examinam os arquivos em busca de assinaturas de malware conhecidas e comportamentos suspeitos, e então tomam medidas para proteger o sistema.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 6,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2023 Banca: CESPE / CEBRASPE - Prefeitura de Boa Vista - RR - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 247,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "No que diz respeito à segurança da informação, a Microsoft recomenda o emprego de determinados critérios para criação de senhas consideradas fortes para uso no ambiente de informática, incluindo a internet. Com esse objetivo, um critério a ser adotado é criar senhas formadas com:",
    "options": [
      "letras maiúsculas, minúsculas e algarismos",
      "o próprio nome, data ou ano de nascimento",
      "siglas, termos ou palavras em idiomas estrangeiros",
      "nomes de pai, filhos ou palavras de fácil memorização"
    ],
    "correct": 0,
    "explanation": "Senhas que contêm uma combinação de letras maiúsculas, minúsculas e algarismos são consideradas mais seguras porque aumentam a complexidade da senha, tornando-a mais difícil de ser quebrada por ataques de força bruta ou tentativas de adivinhação. Entre as alternativas, A é a melhor. Na prática, a mistura de caracteres sozinha não basta: prefira senhas longas, únicas e não previsíveis, com autenticação em dois fatores quando disponível.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 7,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2022 Banca: SELECON - Prefeitura de São Gonçalo - RJ - Guarda Municipal Nível II.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 248,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "Prefeitura de Betim - MG - Guarda Municipal - Masculino e Feminino Assinale a alternativa que apresenta um termo que NÃO corresponde a um tipo comum de vírus ou malware.",
    "options": [
      "Backdoor.",
      "Bot.",
      "Firewall.",
      "Keylogger."
    ],
    "correct": 2,
    "explanation": "Um firewall não é um tipo de vírus ou malware. Na verdade, é uma medida de segurança de rede projetada para monitorar e controlar o tráfego de rede com base em regras de segurança definidas. Ele ajuda a proteger os sistemas contra acessos não autorizados e ataques cibernéticos, mas não é um tipo de software malicioso como os outros mencionados.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 8,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2022 Banca: IBGP Órgão: Prefeitura de Betim - MG Prova: IBGP - 2022 -.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 249,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "Sobre tecnologias computacionais, podemos afirmar que o OneDrive é:",
    "options": [
      "Loja virtual da Microsoft.",
      "Assistente Virtual de Microsoft.",
      "Serviço de armazenamento em nuvem da Microsoft.",
      "Pacote de aplicativos do Office.",
      "Antivírus da Microsoft embutido ao Sistema Operacional."
    ],
    "correct": 2,
    "explanation": "O OneDrive é um serviço de armazenamento em nuvem da Microsoft, que permite aos usuários armazenar, sincronizar e compartilhar arquivos e pastas online. Ele oferece integração com vários dispositivos e aplicativos da Microsoft, facilitando o acesso aos arquivos de qualquer lugar e em qualquer momento.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 9,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: IVIN Órgão: - Prefeitura de Curuçá - PA - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  },
  {
    "id": 250,
    "subject": "inf",
    "topic": "Segurança e nuvem",
    "question": "Referente a definição de \"Armazenamento de Dados na Nuvem (cloud storage)\", assinale a alternativa que apresenta a definição adequada, tecnicamente.",
    "options": [
      "Software de gerenciamento de arquivos",
      "Armazenamento físico em servidores locais",
      "Um tipo de impressora na nuvem",
      "Armazenamento exclusivo para vídeos",
      "Armazenamento de dados online"
    ],
    "correct": 4,
    "explanation": "O armazenamento de dados na nuvem refere-se à prática de salvar, gerenciar e fazer backup de dados em servidores remotos, geralmente hospedados na Internet. Isso permite o acesso aos dados de qualquer lugar com conexão à internet e oferece escalabilidade, segurança e facilidade de gerenciamento. Portanto, a opção E é a definição mais precisa e adequada.",
    "source": "",
    "article": "",
    "imported": true,
    "materialGroup": "Informática · Segurança e nuvem",
    "materialNumber": 10,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: Ano: 2024 Banca: - Prefeitura de Manaus - AM - Técnico Municipal I - Guarda Municipal.",
    "status": "ready",
    "scopeNote": "",
    "revision": "",
    "passage": []
  }
];
IMPORTED.push(...COMPUTING_MATERIAL);
BANK.push(...COMPUTING_MATERIAL);
