// Conteúdo do PDF enviado, com atribuição e notas de revisão.
Object.assign(SOURCES, {dudh:["Declaração Universal dos Direitos Humanos — ONU", "https://www.ohchr.org/en/human-rights/universal-declaration/translations/portuguese"], cadh:["Convenção Americana sobre Direitos Humanos — OEA", "https://www.oas.org/dil/port/tratados_B-32_Convencao_Americana_sobre_Direitos_Humanos.htm"]});
const HUMAN_RIGHTS = [
  {
    "id": 161,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "A Declaração Universal de Direitos Humanos representou um importante marco na história da humanidade ao se ampliar o lastro protetivo sobre a pessoa humana. Nesse contexto, assinale a alternativa que NÃO apresenta um direito assegurado pela referida Declaração de Direitos.",
    "options": [
      "Todo ser humano acusado de um ato delituoso tem o direito de ser presumido inocente até que a sua culpabilidade tenha sido provada por decisão transitada em julgado, em julgamento público no qual lhe tenham sido asseguradas todas as garantias necessárias à sua defesa.",
      "Todo ser humano tem direito à liberdade de opinião e expressão. Esse direito inclui a liberdade de, sem interferência, ter opiniões e de procurar, receber e transmitir informações e ideias por quaisquer meios e independentemente de fronteiras.",
      "Todo ser humano tem direito à liberdade de pensamento, consciência e religião. Esse direito inclui a liberdade de mudar de religião ou crença e a liberdade de manifestar essa religião ou crença pelo ensino, pela prática, pelo culto em público ou em particular.",
      "Ninguém poderá ser culpado por qualquer ação ou omissão que, no momento, não constituíam delito perante o direito nacional ou internacional. Também não será imposta pena mais forte de que aquela que, no momento da prática, era aplicável ao ato delituoso."
    ],
    "correct": 0,
    "explanation": "Nesta questão, o examinador cobrou a exata previsão na DUDH, motivo pelo qual, apesar de a alternativa A não parecer errada de acordo com o ordenamento jurídico brasileiro, não repete exatamente o previsto na Declaração, que assim dispõe: Artigo 11° 1. Toda a pessoa acusada de um ato delituoso presume-se inocente até que a sua culpabilidade fique legalmente provada no decurso de um processo público em que todas as garantias necessárias de defesa lhe sejam asseguradas.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 1,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2022 - IBGP - Prefeitura de Betim - MG - Guarda Municipal - Masculino e Feminino.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 162,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Atente para o seguinte excerto: “Artigo 1 - Todos os seres humanos nascem livres e iguais em dignidade e direitos. São dotados de razão e consciência e devem agir em relação uns aos outros com espírito de fraternidade”. O texto acima foi extraído do documento denominado",
    "options": [
      "Declaração Americana de Direitos Humanos.",
      "Declaração dos Direitos do Homem e Cidadão.",
      "Declaração Universal das Nações Unidas.",
      "Declaração Universal dos Direitos Humanos."
    ],
    "correct": 3,
    "explanation": "Trata-se do artigo 1° da Declaração Universal dos Direitos Humanos (DUDH).",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 2,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2022 - UECE-CEV - 2022 - Prefeitura de Sobral - CE - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 163,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "“O Observatório Sírio para os Direitos Humanos, um grupo de monitoramento com base no Reino Unido e uma rede de fontes na Síria, registrou a morte de 387.118 pessoas até dezembro de 2020, entre elas 116.911 civis. O número de mortos não incluiu as 205.300 pessoas que estavam desaparecidas e presumidamente mortas, entre eles 88 mil civis que teriam morrido em prisões administradas pelo governo onde se praticava entre eles tortura.” (Disponível em https://www.bbc.com/portuguese/ internacional-56378202 - adaptado) Com relação aos países membros signatários da Declaração Universal dos Direitos Humanos - Resolução 217- A (III) da Assembleia Geral das Nações Unidas de 1948, a prática de tortura, de penas ou de tratamentos degradantes em seres humanos, com base nas regras e/ou recomendações contidas nessa Declaração, é:",
    "options": [
      "vedada em qualquer hipótese",
      "permitida apenas na hipótese de guerra civil",
      "permitida apenas na hipótese de calamidade pública",
      "permitida apenas na hipótese de mudança de regime político"
    ],
    "correct": 0,
    "explanation": "Conforme o Artigo 5° da DUDH - Ninguém será submetido a tortura nem a penas ou tratamentos cruéis, desumanos ou degradantes.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 3,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2022 - SELECON - SEJUSP-MG - Policial Penal - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 164,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "“Em pleno século 21, há notícias de resgate de trabalhadores que se sujeitam a trabalhos forçados e condições degradantes em razão da precariedade da situação econômica e social que alcança esse grupo de trabalhadores.” (Disponível em https://noticias.uol.com.br/colunas/leonardo- sakamoto/2021/10/07/resgates-de-escravizados-ja-batem-os-de-2020- e-ganham-a- cara-da-pandemia.htm?cmpid=copiaecola. Acesso em 29/11/2021). Nesse passo, os países signatários da Declaração Universal dos Direitos Humanos - Resolução 217- A (III), da Assembleia Geral das Nações Unidas de 1948, ao permitirem a sujeição do ser humano a trabalhos forçados e condições degradantes:",
    "options": [
      "contrariam regras e/ou recomendações previstas na respectiva Declaração",
      "não contrariam regras e/ou recomendações previstas na respectiva Declaração pela ausência da totalidade de anuência dos países membros signatários desse documento",
      "podem contrariar regras e/ou recomendações previstas na respectiva Declaração no caso de declaração de guerra envolvendo os países membros signatários desse documento",
      "não contrariam regras e/ou recomendações previstas na respectiva Declaração em razão da vigência temporária dessa Declaração limitada ao período do pós-guerra"
    ],
    "correct": 0,
    "explanation": "De acordo com a Declaração Universal dos Direitos Humanos: Artigo 5 - Ninguém será submetido à tortura, nem a tratamento ou castigo cruel, desumano ou degradante. Artigo 23 1. - Todo ser humano tem direito ao trabalho, à livre escolha do trabalho, a condições equitativas e satisfatórias de trabalho e à proteção contra o desemprego.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 4,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2022 - SELECON - SEJUSP-MG - Policial Penal - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 165,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "A respeito e com base na DUDH (Declaração Universal dos Direitos Humanos), assinale a alternativa CORRETA.",
    "options": [
      "A DUDH é um dos mais importantes tratados internacionais sobre direitos humanos, cuja gênese encontra-se vinculada ao contexto histórico do fim da segunda guerra mundial.",
      "A vontade do povo será a base da autoridade do governo, esta vontade será expressa em eleições periódicas e legítimas, por sufrágio universal, por voto secreto ou processo equivalente que assegure a liberdade de voto, sendo imprescindível a filiação partidária.",
      "O direito de organizar sindicatos e de neles ingressar é um direito humano com previsão expressa na DUDH.",
      "A maternidade e a infância têm direito a cuidados e assistência especiais. As crianças nascidas fora do matrimônio, entretanto, gozarão de proteção especial.",
      "O direito humano à liberdade de locomoção não engloba o direito de deixar qualquer país, inclusive o próprio, e a este regressar."
    ],
    "correct": 2,
    "explanation": "Este direito está previsto no art. 23.4 da DUDH: \"Todo ser humano tem direito a organizar sindicatos e a neles ingressar para proteção de seus interesses\".",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 5,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2021 - FAUEL - 2021 - Prefeitura de São José dos Pinhais - PR - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 166,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "No que concerne ao repouso, lazer e férias, é correto afirmar que a Declaração Universal dos Direitos Humanos",
    "options": [
      "não possui qualquer previsão.",
      "possui previsão com relação ao repouso, mas nada consta sobre as férias.",
      "contempla que o repouso, o lazer e as férias são direitos trabalhistas do ser humano.",
      "possui, entre outras, previsão de férias remuneradas periódicas.",
      "possui previsão com relação às férias, mas nada consta sobre o repouso."
    ],
    "correct": 3,
    "explanation": "Segundo a Declaração Universal dos Direitos Humanos: Artigo 24 Todo ser humano tem direito a repouso e lazer, inclusive a limitação razoável das horas de trabalho e a férias remuneradas periódicas.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 6,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: VUNESP - 2020 - Prefeitura de Ferraz de Vasconcelos - SP - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 167,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Nos termos da Declaração Universal dos Direitos Humanos, é correto afirmar que",
    "options": [
      "ninguém será mantido em escravidão, sendo permitida a servidão em algumas situações.",
      "ninguém será submetido a tratamento ou castigo cruel, sendo admitida a tortura apenas em situações excepcionais.",
      "todo ser humano tem o direito de ser, em todos os lugares, reconhecido como pessoa perante a lei.",
      "todo ser humano somente será compelido a fazer parte de associações de fins pacíficos.",
      "todo ser humano tem direito à liberdade de reunião e associação independentemente de sua finalidade."
    ],
    "correct": 2,
    "explanation": "Conforme o Artigo 6° da DUDH: Todos os indivíduos têm direito ao reconhecimento, em todos os lugares, da sua personalidade jurídica.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 7,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2020 - VUNESP - Prefeitura de Ferraz de Vasconcelos - SP - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 168,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "A Declaração Universal de Direitos Humanos de 1948 foi elaborada pela extinta Comissão de Direitos Humanos da Organização das Nações Unidas. Ela era uma das etapas para uma futura elaboração de um “tratado internacional de direitos humanos” que acabou não acontecendo por conta da Guerra Fria. Procurou colocar a dignidade da pessoa humana como núcleo de todos os direitos humanos. Assim, sobre seu âmbito de proteção, assinale a alternativa correta.",
    "options": [
      "Nem todo ser humano tem o direito de ser, em todos os lugares, reconhecido como pessoa perante a lei",
      "O exílio é permitido em determinadas situações",
      "Reconhece a possibilidade da norma retroagir para prejudicar o réu",
      "Todo ser humano acusado de um ato delituoso tem o direito de ser presumido inocente até que a sua culpabilidade tenha sido provada de acordo com a lei, em julgamento público no qual lhe tenha sido asseguradas todas as garantias necessárias à sua defesa",
      "A vontade do povo será a base da autoridade do governo; esta vontade será expressa em eleições periódicas e legítimas, por sufrágio censitário, por voto secreto ou processo equivalente que assegure a liberdade de voto"
    ],
    "correct": 3,
    "explanation": "A DUDH, em seu Artigo 11.1, prevê que: Toda a pessoa acusada de um ato delituoso presume-se inocente até que a sua culpabilidade fique legalmente provada no decurso de um processo público em que todas as garantias necessárias de defesa lhe sejam asseguradas.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 8,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2020 - IBFC - SAEB-BA - Soldado.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 169,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Sobre o tema direitos humanos e responsabilidade do Estado, é correto afirmar:",
    "options": [
      "é vedada a revista íntima, podendo o Estado ser condenado por constrangimento ilegal.",
      "a responsabilidade civil do Estado por erro judiciário, se existente, é subjetiva.",
      "o Estado indenizará o condenado por erro judiciário, assim como o que ficar preso além do tempo fixado na sentença.",
      "o agente penitenciário não pode ser civilmente responsável, em ação estatal de regresso, pelos danos causados ao preso por dolo ou culpa.",
      "o Estado não pode ser condenado por danos morais em razão de deficiências estruturais do sistema penitenciário."
    ],
    "correct": 2,
    "explanation": "Esta assertiva possui previsão constitucional expressa (art. 5º, LXXV).",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 9,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2019 - FEPESE - DEAP - SC - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 170,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Direitos Humanos são os direitos fundamentais da pessoa humana. No regime democrático, toda pessoa deve ter a sua dignidade respeitada e a sua integridade protegida, independentemente da origem, raça, etnia, gênero, idade, condição econômica e social, orientação ou identidade sexual, credo religioso ou convicção política. Com base no contexto acima assinale a alternativa INCORRETA:",
    "options": [
      "Direitos humanos são os direitos e liberdades básicas de todos os seres humanos.",
      "A Declaração Universal dos Direitos Humanos da Organização das Nações Unidas afirma que todos os seres humanos nascem livres e iguais em dignidade e em direitos, dotados de razão e de consciência, e devem agir uns para com os outros em espírito de fraternidade.",
      "Os Direitos Humanos são um verdadeiro marco positivo na história das conquistas dos direitos individuais, porém, estão seriamente ameaçados.",
      "Nenhuma das alternativas."
    ],
    "correct": 3,
    "explanation": "As alternativas A a C trazem afirmações corretas, motivo pelo qual, a alternativa D – Nenhuma das Alternativas – deve ser assinalada como gabarito.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 10,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2019 - Instituto Excelência - Prefeitura de Taubaté - SP - Guarda Civil Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 171,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Assinale a alternativa que está em conformidade com a Declaração Universal dos Direitos Humanos.",
    "options": [
      "Ninguém será arbitrariamente privado de sua nacionalidade, sendo, porém, vedado o direito de mudar de nacionalidade.",
      "O direito de procurar e de gozar asilo em outros países não pode ser invocado em caso de perseguição legitimamente motivada por crimes de direito comum.",
      "Todo ser humano tem direito a receber do poder público remédio contra a violação de direitos fundamentais ainda que não reconhecidos pela Constituição ou pela lei.",
      "O casamento não será válido senão com o livre e pleno consentimento dos nubentes, exceto quando houver livre consenso entre os pais destes.",
      "Todo ser humano tem direito à liberdade de reunião e associação pacífica, inclusive para fins paramilitares."
    ],
    "correct": 1,
    "explanation": "Conforme previsão da DUDH: Artigo 14° 1. Toda a pessoa sujeita a perseguição tem o direito de procurar e de beneficiar de asilo em outros países. 2. Este direito não pode, porém, ser invocado no caso de processo realmente existente por crime de direito comum ou por atividades contrárias aos fins e aos princípios das Nações Unidas.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 11,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2019 - VUNESP - Prefeitura de Campinas - SP - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 172,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "A respeito dos Direitos Humanos assinale verdadeiro ou falso : ( ) Toda pessoa tem capacidade para gozar os direitos e as liberdades estabelecidos nesta Declaração, sem distinção de qualquer espécie, seja de raça, cor, sexo, língua, religião, opinião política ou de outra natureza, origem nacional ou social, riqueza, nascimento, ou qualquer outra condição. ( ) Toda pessoa tem direito à vida, à liberdade e à segurança pessoal. ( ) Todos são iguais perante a lei e têm direito, sem qualquer distinção, a igual proteção da lei. Todos têm direito a igual proteção contra qualquer discriminação que viole a presente Declaração e contra qualquer incitamento a tal discriminação. Assinale a alternativa CORRETA:",
    "options": [
      "V-F-V.",
      "V-V-V.",
      "F-V-F.",
      "Nenhuma das alternativas."
    ],
    "correct": 1,
    "explanation": "Todas as assertivas apresentadas são verdadeiros, com base na DUDH Artigo 2 Todos os seres humanos podem invocar os direitos e as liberdades proclamados na presente Declaração, sem distinção alguma, nomeadamente de raça, de cor, de sexo, de língua, de religião, de opinião política ou outra, de origem nacional ou social, de fortuna, de nascimento ou de qualquer outra situação. Além disso, não será feita nenhuma distinção fundada no estatuto político, jurídico ou internacional do país ou do território da naturalidade da pessoa, seja esse país ou território independente, sob tutela, autônomo ou sujeito a alguma limitação de soberania. Artigo 3 Todo ser humano tem direito à vida, à liberdade e à segurança pessoal. Artigo 7 Todos são iguais perante a lei e tem direito, sem qualquer distinção, a igual proteção da lei. Todos tem direito a igual proteção contra qualquer discriminação que viole a presente Declaração e contra qualquer incitamento a tal discriminação.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 12,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2018 - Instituto Excelência - Prefeitura de Taubaté - SP - Guarda Civil Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 173,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "É correto afirmar que a Declaração Universal dos Direitos Humanos contempla, entre outros, como direito de todo ser humano,",
    "options": [
      "a liberdade de escolha do esporte.",
      "a licença paternidade.",
      "as férias remuneradas periódicas.",
      "a liberdade de reunião pacífica ou não.",
      "o aviso prévio periódico."
    ],
    "correct": 2,
    "explanation": "É a exata previsão do artigo 24 da DUDH.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 13,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2018 - VUNESP - Prefeitura de São Bernardo do Campo - SP - Guarda Civil Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 174,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "A Declaração Universal dos Direitos Humanos",
    "options": [
      "é um conjunto de regras destinado a garantir a impunidade dos criminosos.",
      "não reconhece nenhum direito que seja aplicável às pessoas vítimas de crimes.",
      "não proíbe expressamente a aplicação da pena de morte nem a prisão perpétua para autores de crimes graves.",
      "dispõe que os criminosos devem ser punidos de forma branda porque são vítimas da desigualdade social.",
      "prevê que toda pessoa acusada de crime somente pode ser presa após condenação em segunda instância."
    ],
    "correct": 2,
    "explanation": "A DUDH não veda de forma expressa a aplicação da pena de morte nem a prisão perpétua para autores de crimes graves.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 14,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2018 - FCC - IAPEN-AP - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 175,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Acerca do que dispõe a Declaração Universal dos Direitos Humanos, informe se é verdadeiro (V) ou falso (F) o que se afirma a seguir e assinale a alternativa com a sequência correta. ( ) Todo ser humano tem o direito à saída e ao regresso de qualquer país. ( ) Todo ser humano, vítima de perseguição legitimamente motivada por crimes de direito comum, tem o direito de procurar e de gozar asilo em outros países. ( ) Todo ser humano tem direito à liberdade de locomoção e residência dentro das fronteiras de cada Estado.",
    "options": [
      "V – F – V.",
      "F – V – F.",
      "F – V – V.",
      "F – F – V."
    ],
    "correct": 3,
    "explanation": "Sequência F–F–V. O art. 13 permite sair de qualquer país e regressar ao próprio país, não a qualquer país. O art. 14.2 exclui o asilo por perseguição legitimamente motivada por crimes comuns. A terceira afirmação corresponde ao art. 13.1.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 15,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - INSTITUTO AOCP - SEJUS - CE - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "Revisão: o PDF indica A, mas seu próprio comentário afirma que apenas a terceira proposição é verdadeira. Para o enunciado transcrito, o gabarito de estudo foi corrigido para D.",
    "passage": []
  },
  {
    "id": 176,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Conforme a Declaração Universal dos Direitos Humanos, os direitos humanos são",
    "options": [
      "revogáveis.",
      "absolutos.",
      "renunciáveis.",
      "imprescritíveis.",
      "individuais."
    ],
    "correct": 3,
    "explanation": "A imprescritibilidade é uma característica dos Direitos Humanos, afinal as normas de direitos humanos não se esgotam com o transcurso do tempo.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 16,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - CESPE - SERES-PE - Agente de Segurança Penitenciária.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 177,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "No que concerne a Declaração Universal dos Direitos Humanos, analise as afirmativas a seguir. I. Todo ser humano tem direito a um padrão de vida capaz de assegurar-lhe, e a sua família, saúde e bem-estar, inclusive alimentação, vestuário, habitação, cuidados médicos e os serviços sociais indispensáveis, e direito à segurança em caso de desemprego, doença, invalidez, viuvez, velhice ou outros casos de perda dos meios de subsistência em circunstâncias fora de seu controle. II. Todo ser humano que trabalha tem direito a uma remuneração justa e satisfatória, que lhe assegure, assim como à sua família, uma existência compatível com a dignidade humana, ao que é vedado acrescer outros meios de proteção social. III. Todo ser humano tem direito à instrução. A instrução será gratuita, pelo menos nos graus elementares e fundamentais. A instrução elementar será obrigatória. A instrução técnico-profissional será acessível a todos, bem como a instrução superior, esta, baseada no mérito. Está(ão) correta(s) apenas a(s) afirmativa(s)",
    "options": [
      "I.",
      "III.",
      "I e II.",
      "I e III."
    ],
    "correct": 3,
    "explanation": "Vejamos como prevê a DUDH: Artigo 25° 1. Toda a pessoa tem direito a um nível de vida suficiente para lhe assegurar e à sua família a saúde e o bem-estar, principalmente quanto à alimentação, ao vestuário, ao alojamento, à assistência médica e ainda quanto aos serviços sociais necessários, e tem direito à segurança no desemprego, na doença, na invalidez, na viuvez, na velhice ou noutros casos de perda de meios de subsistência por circunstâncias independentes da sua vontade. Artigo 26° 1. Toda a pessoa tem direito à educação. A educação deve ser gratuita, pelo menos a correspondente ao ensino elementar fundamental. O ensino elementar é obrigatório. O ensino técnico e profissional dever ser generalizado; o acesso aos estudos superiores deve estar aberto a todos em plena igualdade, em função do seu mérito.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 17,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - IDECAN - SEJUC-RN - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 178,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Quanto à Declaração Universal dos Direitos Humanos, analise as afirmativas a seguir. I. Todo ser humano tem direito à liberdade de pensamento, consciência e religião; este direito inclui a liberdade de mudar de religião ou crença e a liberdade de manifestar essa religião ou crença, pelo ensino, pela prática, pelo culto e pela observância, em público ou em particular. II. Todo ser humano tem direito à liberdade de opinião e expressão; este direito inclui a liberdade de, sem interferência, ter opiniões e de procurar, receber e transmitir informações e ideias por quaisquer meios e independentemente de fronteiras. III. Todo ser humano tem o direito de fazer parte no governo de seu país diretamente ou por intermédio de representantes livremente escolhidos. Está(ão) correta(s) a(s) afirmativa(s)",
    "options": [
      "I, II e III.",
      "I, apenas.",
      "III, apenas.",
      "I e II, apenas."
    ],
    "correct": 0,
    "explanation": "Todas as afirmativas estão corretas nos termos da DUDH.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 18,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - IDECAN - SEJUC-RN - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 179,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Conforme expressa previsão na Declaração Universal dos Direitos Humanos, ninguém",
    "options": [
      "será submetido à tortura.",
      "será preso, detido ou exilado.",
      "pode mudar de nacionalidade.",
      "pode reunir-se sem autorização."
    ],
    "correct": 0,
    "explanation": "Assim prevê a DUDH: Artigo 5° - Ninguém será submetido a tortura nem a penas ou tratamentos cruéis, desumanos ou degradantes",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 19,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - IDECAN - 2017 - SEJUC-RN - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 180,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "A Declaração Universal dos Direitos Humanos estabelece que todo ser humano acusado de um ato delituoso tem o direito de ser presumido inocente até que a sua culpabilidade tenha sido provada de acordo com a lei, em julgamento público no qual lhe tenham sido asseguradas todas as garantias necessárias à sua defesa. A interpretação dessa norma, em face da Constituição brasileira, permite afirmar que",
    "options": [
      "é vedada a prisão de qualquer cidadão antes do trânsito em julgado da ação condenatória penal.",
      "ninguém pode ser investigado, denunciado ou condenado com base, unicamente, em provas ilícitas.",
      "a ampla defesa deve ser interpretada de modo restrito, pois não alcança as fases recursais no processo.",
      "o fato de o réu estar sendo processado por outros crimes é suficiente para condená- lo nos demais processos."
    ],
    "correct": 1,
    "explanation": "A interpretação da norma da Declaração Universal dos Direitos Humanos mencionada no contexto implica que todo acusado de um ato delituoso tem o direito de ser presumido inocente até que sua culpabilidade seja provada de acordo com a lei, em um julgamento público onde lhe sejam asseguradas todas as garantias necessárias à sua defesa. Nesse sentido, a Constituição brasileira também protege esse princípio. Em decorrência, ninguém pode ser investigado, denunciado ou condenado com base exclusivamente em provas ilícitas.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 20,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - IDECAN - 2017 - SEJUC-RN - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 181,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "A Declaração Universal dos Direitos Humanos estabelece que todos os seres humanos nascem livres e iguais em dignidade e direitos. A interpretação dessa norma, em face da Constituição brasileira, permite afirmar que",
    "options": [
      "é constitucional a atribuição supervalorizada de pontos na prova de títulos em concurso público.",
      "as ações afirmativas que estabelecem cotas em concurso são repudiadas na jurisprudência pátria.",
      "os direitos fundamentais têm caráter absoluto, mesmo em face do princípio de convivência das liberdades.",
      "o direito à saúde é direito de todos e representa consequência constitucional indissociável do direito à vida."
    ],
    "correct": 3,
    "explanation": "O direito a saúde decorre do direito constitucional à vida, motivo pelo qual encontra-se correta a alternativa D.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 21,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - IDECAN - SEJUC-RN - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 182,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Nos termos expressos da Declaração Universal dos Direitos Humanos, o fundamento da liberdade, da justiça e da paz no mundo encontra amparo no(a):",
    "options": [
      "Prescindibilidade de proteção dos direitos fundamentais da pessoa humana.",
      "Reconhecimento de que todos os países signatários abominam a pena de morte.",
      "Poder soberano dos países signatários da declaração universal dos direitos humanos.",
      "Dignidade inerente a todos os membros da família humana e de seus direitos iguais e inalienáveis."
    ],
    "correct": 3,
    "explanation": "Essa previsão encontra-se também no preâmbulo da DUDH: “Considerando que o reconhecimento da dignidade inerente a todos os membros da família humana e dos seus direitos iguais e inalienáveis constitui o fundamento da liberdade, da justiça e da paz no mundo”.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 22,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - IDECAN - SEJUC-RN - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 183,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Sobre a Declaração Universal dos Direitos Humanos, é correto afirmar que:",
    "options": [
      "não trata da liberdade religiosa.",
      "não faz referência a direitos políticos.",
      "foi editada em 1958.",
      "é vinculante em sua integral idade, por se tratar de resolução da Organização das Nações Unidas.",
      "prega os ideais de liberdade, igualdade e fraternidade."
    ],
    "correct": 4,
    "explanation": "A alternativa encontra fundamento no art. 1º da DUDH: Artigo 1° Todos os seres humanos nascem livres e iguais em dignidade e em direitos. Dotados de razão e de consciência, devem agir uns para com os outros em espírito de fraternidade.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 23,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - IBADE - SEJUDH - MT - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 184,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Para Norberto Bobbio, a Declaração Universal dos Direitos Humanos foi uma inspiração e orientação para o crescimento da sociedade internacional, com o principal objetivo de torná‐la num Estado e fazer também com que os seres humanos fossem iguais e livres. A respeito de seus termos, é INCORRETO afirmar que",
    "options": [
      "é admitida a conduta arbitrária, quando se trata de caso de exílio.",
      "ninguém será submetido à tortura nem a penas ou tratamentos cruéis, desumanos ou degradantes.",
      "o documento defende que todos têm o direito de receber dos tribunais nacionais competentes remédio efetivo para os atos que violem os direitos fundamentais, não apenas aqueles que lhe sejam reconhecidos pela constituição, como também pela lei.",
      "todo aquele que for vítima de perseguição tem o direito de procurar e de gozar asilo em outros países, exceto quando esta for legitimamente motivada por crimes de direito comum ou por atos contrários aos propósitos e princípios das Nações Unidas."
    ],
    "correct": 0,
    "explanation": "A altermativa está incorreta uma vez que não é admitida a conduta arbitrária.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 24,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2015 - CONSULPLAN - Prefeitura de Belo Horizonte - MG - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 185,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "O reconhecimento dos princípios fundamentais, dos direitos e da dignidade da pessoa proclamados na Declaração Universal dos Direitos Humanos (1948), é necessário para garantir a liberdade, a justiça e a paz no mundo. Desses princípios decorre que:",
    "options": [
      "a segurança pessoal é um direito restrito àqueles que podem pagar por ela, a qual é reconhecida como segurança privada.",
      "a proteção da lei é um direito restrito àqueles que são assistidos por um advogado que interpreta a lei e exige seu cumprimento.",
      "a presunção de inocência é um princípio restrito aos julgamentos nos tribunais sem aplicação aos casos de detenção para fins de averiguação.",
      "a ordem pública é um princípio capaz de restringir os direitos e as liberdades do indivíduo, conforme limitações legais."
    ],
    "correct": 3,
    "explanation": "Conforme o artigo 29 da DUDH: Artigo 29° 1. O indivíduo tem deveres para com a comunidade, fora da qual não é possível o livre e pleno desenvolvimento da sua personalidade. No exercício deste direito e no gozo destas liberdades ninguém está sujeito senão às limitações estabelecidas pela lei com vista exclusivamente a promover o reconhecimento e o respeito dos direitos e 2. liberdades dos outros e a fim de satisfazer as justas exigências da moral, da ordem pública e do bem-estar numa sociedade democrática. 3. Em caso algum estes direitos e liberdades poderão ser exercidos contrariamente e aos fins e aos princípios das Nações Unidas.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 25,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2014 - UFGD - Prefeitura de Senador Canedo - GO - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 186,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Segundo o texto da Declaração Universal dos Direitos Humanos, a proteção à privacidade compreende:",
    "options": [
      "Somente a privacidade do próprio interessado.",
      "A privacidade do próprio interessado, da sua família, no seu lar ou na sua correspondência.",
      "A privacidade do próprio interessado, da sua família e do seu local de trabalho.",
      "A privacidade do próprio interessado e das pessoas que mantenham relação de afnidade com ele."
    ],
    "correct": 1,
    "explanation": "É o que prevê o artigo 12 da DUDH: Artigo 12° Ninguém sofrerá intromissões arbitrárias na sua vida privada, na sua família, no seu domicílio ou na sua correspondência, nem ataques à sua honra e reputação. Contra tais intromissões ou ataques toda a pessoa tem direito a proteção da lei.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 26,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2014 - IBFC - SEAP-MG - Agente de Segurança Penitenciária.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 187,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Complete as lacunas, de acordo com a alternativa que refete o texto da Declaração Universal dos Direitos Humanos: “Artigo I - Todas as pessoas nascem livres e iguais em ________________________. São dotadas de razão e _______________________ e devem agir em relação umas às outras com espírito de ____________________.”",
    "options": [
      "Dignidade e direitos – consciência – fraternidade.",
      "Direitos e deveres – liberdade – solidariedade.",
      "Direitos e obrigações – convicção – solidariedade.",
      "Dignidade e obrigações – consciência – harmonia."
    ],
    "correct": 0,
    "explanation": "Vejamos na íntegra o artigo 1º da DUDH: Artigo 1° Todas as pessoas nascem livres e iguais em dignidade e em direitos. São dotadas de razão e de consciência e devem agir em relação umas às outras com espírito de fraternidade.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 27,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2014 - IBFC - SEAP-MG - Agente de Segurança Penitenciária.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 188,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Com relação aos direitos previstos na Declaração, considere as afirmativas a seguir. I. O Estado tem prioridade de direito na escolha do gênero de instrução que será ministrada para as crianças e os estudantes. II. Toda pessoa tem direito à liberdade de locomoção e à residência dentro das fronteiras de cada Estado. III. Toda pessoa tem deveres para com a comunidade, em que o livre e pleno desenvolvimento de sua personalidade é possível. IV. Os homens e as mulheres de maior idade, sem qualquer restrição de raça, nacionalidade ou religião, têm o direito de contrair matrimônio e fundar uma família. Gozam de iguais direitos em relação ao casamento, sua duração e sua dissolução. Assinale a alternativa correta.",
    "options": [
      "Somente as afirmativas I e II são corretas.",
      "Somente as afirmativas I e IV são corretas.",
      "Somente as afirmativas III e IV são corretas.",
      "Somente as afirmativas I, II e III são corretas.",
      "Somente as afirmativas II, III e IV são corretas."
    ],
    "correct": 4,
    "explanation": "A única assertiva incorreta é a I, uma vez que os pais pertence a prioridade do direito de escolher o gênero de educação a dar aos filhos (art. 26 da DUDH).",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 28,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: COPS-UEL - SEAP-PR - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 189,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Em sintonia com o Art. XXIII da Declaração Universal dos Direitos Humanos, considere as afirmativas a seguir. I. Toda pessoa tem direito ao trabalho, à livre escolha de emprego, a condições justas e favoráveis de trabalho e à proteção contra o desemprego. II. Toda pessoa que trabalhe tem direito a uma remuneração justa e satisfatória, que lhe assegure, assim como à sua família, uma existência compatível com a dignidade humana, e a que se acrescentarão, se necessário, outros meios de proteção social. III. Toda pessoa tem direito a organizar sindicatos e neles ingressar para proteção de seus interesses. IV. Toda pessoa, ao realizar trabalho igual a outra, tem direito a remuneração diferente, motivada por distinção de nacionalidade. Assinale a alternativa correta.",
    "options": [],
    "correct": null,
    "explanation": "A assertiva IV está errada, pois fala em remuneração diferente, quando, na verdade, deve ser igual.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 29,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: COPS-UEL - SEAP-PR - Agente Penitenciário.",
    "status": "pending",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "Questão incompleta no PDF: as proposições foram preservadas, mas faltam as alternativas. Não participa de treinos nem pontua. O comentário do arquivo considera a proposição IV incorreta.",
    "passage": [],
    "sourceAnswer": "D (alternativas ausentes no PDF)"
  },
  {
    "id": 190,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Com relação à Declaração Universal dos Direitos Humanos, adotada e proclamada pela Assembleia Geral das Nações Unidas, em 1948, analise as afirmativas a seguir. I. Ninguém será submetido à tortura nem a tratamento ou castigo cruel, desumano ou degradante, salvo quando suspeito de ter cometido crime hediondo. II. Toda pessoa tem direito, sem qualquer distinção, a igual proteção da lei, exceto quando suspeito de envolvimento em atos lesivos à ordem pública. III. Toda pessoa acusada de ato delituoso tem o direito de ser presumida inocente, até que sua culpabilidade venha a ser provada de acordo com a lei. Assinale:",
    "options": [
      "se somente a afirmativa I estiver correta.",
      "se somente a afirmativa II estiver correta.",
      "se somente a afirmativa III estiver correta.",
      "se somente as afirmativas I e II estiverem corretas.",
      "se somente as afirmativas II e III estiverem corretas."
    ],
    "correct": 2,
    "explanation": "Somente a assertiva III está correta, possuindo fundamento no artigo 11.1 da DUDH.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 30,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: FGV - SEGEP-MA - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 191,
    "subject": "leg",
    "topic": "Direitos Humanos · DUDH",
    "question": "Assinale a alternativa que contempla a instituição que criou a Declaração Universal dos Direitos Humanos.",
    "options": [
      "Mercosul",
      "Comunidade Europeia",
      "Organização do Tratado Norte",
      "Organização das Nações Unidas",
      "Organização dos Estados Americanos"
    ],
    "correct": 3,
    "explanation": "A Declaração foi proclamada pela Assembleia Geral das Nações Unidas em Paris, em 10 de Dezembro de 1948, através da Resolução 217 A (III) da Assembleia Geral.",
    "source": "dudh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · DUDH",
    "materialNumber": 31,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: FEPESE - SJC-SC - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 192,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "A instituição judicial autônoma cujo objetivo é aplicar e interpretar a Convenção Americana denomina-se",
    "options": [
      "Assembleia Geral da OEA",
      "Corte Interamericana de Direitos Humanos.",
      "Pacto de San José da Costa Rica.",
      "Suprema Corte dos Estados Americanos."
    ],
    "correct": 1,
    "explanation": "A Corte Interamericana de Direitos Humanos aplica e interpreta a Convenção Americana. É a alternativa B; “Pacto de San José” é o nome do tratado, não da instituição judicial.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 1,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2022 - UECE-CEV - Prefeitura de Sobral - CE - Guarda Municipal.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "Revisão: o PDF assinala C, mas seu comentário identifica a Corte, que aparece na alternativa B. Gabarito de estudo corrigido para B.",
    "passage": []
  },
  {
    "id": 193,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "A Convenção Americana sobre Direitos Humanos, Pacto de São José da Costa Rica, determina que não se deve impor a pena de morte à pessoa que, no momento da perpetração do delito, for menor de ________ anos, ou maior de __________ anos, nem aplicá-la à mulher em estado de gravidez. Assinale a alternativa que preenche, correta e respectivamente, as lacunas do trecho acima.",
    "options": [
      "18 (dezoito) – 60 (sessenta)",
      "18 (dezoito) – 70 (setenta)",
      "16 (dezesseis) – 60 (sessenta)",
      "16 (dezesseis) – 70 (setenta)",
      "21 (vinte e um) – 70 (setenta)"
    ],
    "correct": 1,
    "explanation": "Conforme artigo 4.5 do Pacto de São José da Costa Rica: Não se deve impor a pena de morte a pessoa que, no momento da perpetração do delito, for menor de dezoito anos, ou maior de setenta, nem aplicá-la a mulher em estado de gravidez.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 2,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2022 - FUNDATEC - SUSEPE-RS - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "Referência corrigida: art. 4.5 da Convenção Americana.",
    "passage": []
  },
  {
    "id": 194,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "Sobre “Garantias Judiciais”, a Convenção Americana de Direitos Humanos (“Pacto de San José da Costa Rica”), prevê que toda pessoa acusada de delito tem direito a que se presuma sua inocência enquanto não se comprove legalmente sua culpa. Durante o processo, toda pessoa tem direito, em plena igualdade, de:",
    "options": [
      "ser torturada.",
      "ficar por pelo menos 5 (cinco) dias incomunicável.",
      "confessar o crime, mesmo que seja coagida a fazê-lo.",
      "não ser obrigada a depor contra si mesma, nem a declarar-se culpada.",
      "não ser assistido por um defensor, ainda que deseje o auxílio de um."
    ],
    "correct": 3,
    "explanation": "Artigo 8.2.g do Pacto de São José da Costa Rica: Direito de não ser obrigado a depor contra si mesma, nem a declarar-se culpada.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 3,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2020 - IBADE - Prefeitura de Cariacica - ES - Guarda Municipal I.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "Referência corrigida: art. 8.2.g da Convenção Americana.",
    "passage": []
  },
  {
    "id": 195,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "A Convenção Americana de Direitos Humanos, também chamado de Pacto de San José da Costa Rica, foi assinado em 22 de novembro de 1969 e ratificado pelo Brasil em setembro de 1992. Ela busca consolidar entre os países americanos um regime de liberdade pessoal e justiça pessoal, fundado no respeito aos direitos humanos essenciais, independentemente do país onde a pessoa resida ou tenha nascido. Assim, quanto ao seu âmbito de proteção, analise as afirmativas abaixo e dê valores Verdadeiro (V) ou Falso (F). ( ) Não existe nenhuma relação entre o Pacto de San Jose da Costa Rica e a Declaração Universal dos Direitos Humanos. ( ) Sobre os deveres das pessoas, determina que toda pessoa tem deveres para com a família, a comunidade e a humanidade. ( ) Toda pessoa tem direito a um recurso simples e rápido ou a qualquer outro recurso efetivo, perante os juízes ou tribunais competentes, que a proteja contra atos que violem seus direitos fundamentais reconhecidos pela constituição, pela lei ou pela presente Convenção, mesmo quando tal violação seja cometida por pessoas que estejam atuando no exercício de suas funções oficiais. ( ) Algumas disposições do Pacto de San José da Costa Rica podem excluir outros direitos e garantias que são inerentes ao ser humano ou que decorrem da forma democrática representativa de governo. Assinale a alternativa que apresenta a sequência correta de cima para baixo.",
    "options": [
      "V, V, V, V",
      "V, V, F, F",
      "V, F, F, V",
      "F, F, V, V",
      "F, V, V, F"
    ],
    "correct": 4,
    "explanation": "As afirmativas II e III são verdadeiras por estarem em consonância, respectivamente com o artigo 32.1 e 25.1 do Pacto de São José da Costa Rica. Artigo 32. 1. Toda pessoa tem deveres para com a família, a comunidade e a humanidade. Artigo 25. 1. Toda pessoa tem direito a um recurso simples e rápido ou a qualquer outro recurso efetivo, perante os juízes ou tribunais competentes, que a proteja contra atos que violem seus direitos fundamentais reconhecidos pela constituição, pela lei ou pela presente Convenção, mesmo quando tal violação seja cometida por pessoas que estejam atuando no exercício de suas funções oficiais.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 4,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2020 - IBFC - SAEB-BA - Soldado.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 196,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "Considere as seguintes disposições de tratados internacionais de direitos humanos: ◾ Art. 7.5 da Convenção Interamericana de Direitos Humanos: “Toda pessoa detida ou retida deve ser conduzida, sem demora, à presença de um juiz ou outra autoridade autorizada pela lei a exercer funções judiciais e tem direito a ser julgada dentro de um prazo razoável ou a ser posta em liberdade, sem prejuízo de que prossiga o processo. Sua liberdade pode ser condicionada a garantias que assegurem o seu comparecimento em juízo”. ◾ Art. 9.3 do Pacto dos Direitos Civis e Políticos: “Qualquer pessoa presa ou encarcerada em virtude de infração penal deverá ser conduzida, sem demora, à presença do juiz ou de outra autoridade habilitada por lei a exercer funções judiciais e terá o direito de ser julgada em prazo razoável ou de ser posta em liberdade. A prisão preventiva de pessoas que aguardam julgamento não deverá constituir a regra geral, mas a soltura poderá estar condicionada a garantias que assegurem o comparecimento da pessoa em questão à audiência, a todos os atos do processo e, se necessário for, para a execução da sentença”. As disposições descritas se referem à:",
    "options": [
      "audiência preliminar.",
      "audiência de conciliação.",
      "audiência de instrução e julgamento.",
      "audiência admonitória.",
      "audiência de custódia."
    ],
    "correct": 4,
    "explanation": "Trata-se da chamada audiência de custódia.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 5,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2019 - FEPESE - SJC-SC - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 197,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "A Convenção Americana sobre Direitos Humanos estabelece que “são competentes para conhecer dos assuntos relacionados com o cumprimento dos compromissos assumidos pelos Estados partes nesta Convenção”:",
    "options": [
      "a Organização dos Estados Americanos e o Protetorado Regional de Direitos Humanos.",
      "todas as cortes supremas dos Estados partes quando acionadas pela Procuradoria Americana de Direitos Humanos.",
      "o Tribunal Penal Internacional e o Comitê Americano de Direitos Humanos.",
      "o Alto Comissariado Latino-Americano e a Corte Federal de Direitos Humanos.",
      "a Comissão Interamericana de Direitos Humanos e a Corte Interamericana de Direitos Humanos."
    ],
    "correct": 4,
    "explanation": "Conforme o Pacto de São José da Costa Rica em seu Artigo 33 - São competentes para conhecer dos assuntos relacionados com o cumprimento dos compromissos assumidos pelos Estados Partes nesta Convenção: a. a Comissão Interamericana de Direitos Humanos, doravante denominada a Comissão; e b. a Corte Interamericana de Direitos Humanos, doravante denominada a Corte.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 6,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2018 - FCC - 2018 - IAPEN-AP - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 198,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "Considerando a Convenção Americana sobre Direitos Humanos, é correto afirmar que:",
    "options": [
      "a pena de morte não pode ser restabelecida nos Estados em que tenha sido abolida.",
      "estabelece que o direito à reunião não se submete à qualquer restrição.",
      "o Brasil não é signatário desta Convenção.",
      "permite a escravidão",
      "não trata de delitos ou de direitos políticos."
    ],
    "correct": 0,
    "explanation": "O art. 4.3 proíbe restabelecer a pena de morte nos Estados que a aboliram.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 7,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: 2017 - IBADE - SEJUDH - MT - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "Referência corrigida para art. 4.3; o art. 4.2 transcrito no PDF aborda outra restrição à pena de morte.",
    "passage": []
  },
  {
    "id": 199,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "Na Organização dos Estados Americanos, qual dos tratados internacionais sobre Direitos Humanos prevê a proteção, a preservação e o melhoramento do meio ambiente?",
    "options": [
      "Rio+20",
      "Declaração de San José da Costa Rica",
      "Protocolo Adicional à Convenção Americana sobre Direitos Humanos",
      "Protocolo de Cruz Alta sobre Direitos Humanos",
      "Protocolo de Assunção sobre Direitos Humanos"
    ],
    "correct": 2,
    "explanation": "O Protocolo Adicional à Convenção Americana sobre Direitos Humanos em matéria de Direitos Econômicos, Sociais e Culturais, de 1988 prevê: Artigo 11. Direito a um meio ambiente sadio 1.Toda pessoa tem direito a viver em meio ambiente sadio e a contar com os serviços públicos básicos. 2. Os Estados Partes promoverão a proteção preservação e melhoramento do meio ambiente.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 8,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: FEPESE - SJC-SC - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  },
  {
    "id": 200,
    "subject": "leg",
    "topic": "Direitos Humanos · Convenção Americana",
    "question": "Assinale a alternativa correta acerca da denominação da Convenção Americana de Direitos Humanos de 1969.",
    "options": [
      "Rio 92.",
      "Declaração de Lima.",
      "Protocolo de Olivos.",
      "Pacto de Viña del Mar.",
      "Pacto San José da Costa Rica."
    ],
    "correct": 4,
    "explanation": "A Convenção Americana Sobre Direitos Humanos foi assinada na Conferência Especializada Interamericana sobre Direitos Humanos, em San José, Costa Rica, no dia 22 de novembro de 1969.",
    "source": "cadh",
    "article": "",
    "imported": true,
    "materialGroup": "Direitos Humanos · Convenção Americana",
    "materialNumber": 9,
    "origin": "Material enviado: Leges Concursos · Maane Martins. Atribuição no PDF: FEPESE - SJC-SC - Agente Penitenciário.",
    "status": "extra",
    "scopeNote": "Treino complementar de Direitos Humanos. A inclusão deste material não confirma cobrança destes tratados no edital da GCM Guarulhos/IBAM.",
    "revision": "",
    "passage": []
  }
];
IMPORTED.push(...HUMAN_RIGHTS);
BANK.push(...HUMAN_RIGHTS);
